name: Dependabot composer diff
description: Posts a comment with a diff when Composer dependencies are updated
inputs:
  token:
    required: true
    default: ${{ github.token }}
    description: GitHub token to post the comment with
outputs:
  diff:
    description: The generated diff
runs:
  using: docker
  image: Dockerfile
  env:
    GITHUB_TOKEN: ${{ inputs.token }}
    PULL_REQUEST: ${{ github.event.number }}
