name: Dependabot composer diff
description: Posts a comment with a diff when Composer dependencies are updated
inputs:
  token:
    required: true
    default: ${{ github.token }}
    description: GitHub token to post the comment with
  pull_request:
    required: true
    default: ${{ github.event.number }}
    description: The pull request to post the comment to. This defaults to the current PR and should not be changed.
outputs:
  diff:
    description: The generated diff
runs:
  using: docker
  image: Dockerfile
  env:
    GITHUB_TOKEN: ${{ inputs.token }}
    PULL_REQUEST: ${{ inputs.pull_request }}
